config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#index'
  resources :developers do
    resources :pets, except: [:destroy, :show, :index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/developer.rb
class Developer < ApplicationRecord
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, email: true, uniqueness: true
  validates :pets, length: { maximum: 5 }

  has_many :pets

  def pets_limit_reached?
    pets.count >= 5
  end

  def name
    "#{first_name} #{last_name}"
  end
end

app/models/pet.rb
class Pet < ApplicationRecord
  validates :name, presence: true
  validates :gender, presence: true
  validates :category, presence: true
  validates :age, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 0
  }
  validates_associated :developer

  enum category: [:Dog, :Cat, :Rat, :Chinchilla]
  enum gender: [:Male, :Female]

  belongs_to :developer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController
  helper_method :developer, :developers

  def index; end

  def show; end

  def edit; end

  def create
    save_or_render(:new, :created)
  end

  def update
    save_or_render(:edit, :updated)
  end

  def destroy
    developer.destroy!
    flash_and_redirect :deleted
  end

  private

  def flash_and_redirect(msg)
    flash[:notice] = "Developer #{developer.name} has been #{msg}"
    redirect_to developers_path
  end

  def save_or_render(action, msg)
    if developer.update_attributes(developer_params)
      flash_and_redirect msg
    else
      render action
    end
  end

  def developer_params
    @developer_params ||= params
                          .require(:developer)
                          .permit(:first_name, :last_name, :email, :pet)
  end

  def developer
    @developer ||= Developer.find_or_initialize_by(id: params[:id])
  end

  def developers
    @developers ||= Developer.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @pets = Pet.all
  end
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
  helper_method :developer, :pet

  def show; end

  def new
    return unless developer.pets_limit_reached?

    flash[:error] = 'Pet limit reached, please upgrade to premium plan'
    redirect_to developer_path(developer)
  end

  def edit; end

  def create
    save_or_render(:new, :created)
  end

  def update
    save_or_render(:edit, :updated)
  end

  private

  def save_or_render(action, msg)
    if pet.update_attributes(pet_params)
      flash_and_redirect msg
    else
      render action
    end
  end

  def flash_and_redirect(msg)
    flash[:notice] = "Pet #{pet.name} owned by #{developer.name} was #{msg}"
    redirect_to developer_path(developer)
  end

  def developer
    @developer ||= Developer.find(params[:developer_id])
  end

  def pet
    @pet ||= Pet.find_or_initialize_by(id: params[:id])
  end

  def pet_params
    @pet_params = params
                  .require(:pet).permit(:name, :age, :gender, :category, :alive)
                  .merge('developer_id': developer.id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def icon_link_button(icon, link, options = {})
    link_to(raw("<i class='material-icons'>#{icon}</i>"), link, options)
  end

  def sweet_alert_delete(route, msg, options = {})
    default_options = sweet_alert_delete_params(msg)
    icon_link_button('delete', route, default_options.deep_merge(options))
  end

  def sweet_alert_delete_params(msg) # rubocop:disable Metrics/MethodLength
    {
      method: 'delete',
      data: {
        'sweet-alert-confirm': msg,
        'cancel-button-text': 'No way',
        'confirm-button-color': '#26A69A',
        'sweet-alert-type': 'warning',
        'confirm-button-text': 'Yes, delete it!',
        'allow-outside-click': true
      }
    }
  end
end

app/helpers/developers_helper.rb
module DevelopersHelper
end

app/helpers/navbar_helper.rb
module NavbarHelper
  def navbar_menu(items)
    content_tag :ul do
      items.collect { |item| concat(menu_item(item)) }
    end
  end

  def menu_item(item)
    content_tag(:li, menu_link(item), class: menu_item_status_class(item))
  end

  def menu_item_status_class(item)
    controller_name.in?(item[:controllers]) ? 'active' : ''
  end

  def menu_link(item)
    link_to(item[:label].to_s, item[:path].to_s)
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pets_helper.rb
module PetsHelper
end

app/views/developers/_form.html.erb
<%= render 'layouts/errors', :errors => developer.errors %>
<div class="row">
  <div class="col m12">
    <div class="card-panel white">
      <%= form_for developer, url: url, method: method do |f| %>
          <%= f.label :first_name %>
          <%= f.text_field :first_name %>
          <%= f.label :last_name %>
          <%= f.text_field :last_name %>
          <%= f.label :email %>
          <%= f.text_field :email %>
          <%= f.submit :class => 'btn btn-primary white-text' %>
          <%= link_to('back', _back_url, :class => 'btn red')%>
      <% end %>
    </div>
  </div>
</div>

app/views/developers/edit.html.erb
<%= render 'developers/form', :url => developer_path(developer), :method => 'patch' %>

app/views/developers/index.html.erb
<ul class="collection with-header">
  <li class="collection-header"><h4>Developers</h4></li>
  <% developers.each do |developer| %>
      <li class="collection-item">
        <div>
          <%= developer.name %>
          <%= sweet_alert_delete(developer_path(developer), 'Are you sure to delete this developer?', :class => 'secondary-content red-text') %>
          <%= icon_link_button('edit', edit_developer_path(developer), :class => 'secondary-content') %>
          <%= icon_link_button('pets', developer_path(developer), :class => 'secondary-content blue-text') %>
        </div>
      </li>
  <% end %>
</ul>
<%= icon_link_button('add', developer_path('new'), :class => 'center btn-floating tomato') %>

app/views/developers/new.html.erb
<%= render 'developers/form', :url => developers_path, :method => 'post' %>

app/views/developers/show.html.erb
<div class="row">
  <div class="col m12">
    <div class="card-panel white">
      <h4> <%= developer.name %> </h4>
      <span> <%= developer.email %> </span>
      <ul class="collection">
        <% developer.pets.each do |pet| %>
            <li class="collection-item">
              <div>
                <%= pet.name %>
                <%= icon_link_button('edit', edit_developer_pet_path(developer, pet), :class => 'secondary-content') %>
              </div>
            </li>
        <% end %>
      </ul>

      <%=  link_to(raw('<i class="material-icons">pets</i>Add Pet'),
                  new_developer_pet_path(developer),
                  :class => 'btn btn-primary white-text',
                  :disabled => developer.pets_limit_reached? ) %>

      <% if developer.pets_limit_reached? %>
        <h5>Pet limit reached, please upgrade to premium plan</h5>
      <% end %>
    </div>
  </div>
</div>

app/views/home/index.erb
<div class="row">
  <% @pets.each do |pet| %>
    <div class="col s12 m4">
      <div class="card">
        <div class="card-image">
          <img src="/images/<%= pet.category %>.jpg">
        </div>
        <div class="card-content">
          <p><%= "#{pet.name} - #{pet.age} years #{pet.alive? ? '' : 'R.I.P.'}" %></p>
          <img src="/images/<%= pet.gender %>.png" alt="" />
        </div>
        <div class="card-action">
          <a href="<%= developer_path(pet.developer) %>"><%= pet.developer.name %></a>
        </div>
      </div>
    </div>
  <% end %>
</div>
            

app/views/layouts/_errors.html.erb
<% if errors.any? %>
    <div class="row">
      <div class="col m12">
        <div class="card-panel red darken-4 white-text error-card">
          <ul>
            <% errors.full_messages.each do |msg| %>
                <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      </div>
    </div>
<% end %>

app/views/layouts/_flash.html.erb
<% if flash[:notice] %>
  <script>
    $(document).ready(function () {
      swal({
          title: 'Nice!!',
          text: '<%= flash[:notice] %>',
          type: 'success',
          allowEscapeKey: true,
          allowOutsideClick: true,
          timer: 2000
      });
    });
  </script>
<% end %>

<% if flash[:error] %>
    <script>
        $(document).ready(function () {
            swal({
                title: 'Ouuch!!',
                text: '<%= flash[:error] %>',
                type: 'error',
                allowEscapeKey: true,
                allowOutsideClick: true
            });
        });
    </script>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="footer white-text">
  <div class="footer-copyright">
    <div class="container">
      © 2017 Alexia Torres
    </div>
  </div>
</footer>

app/views/layouts/_navbar.html.erb
<header class="header">
  <nav>
    <div class="nav-wrapper">
      <a href="<%= root_path %>" class="brand-logo center">
        <i class="material-icons">pets</i>
      </a>
      <%= navbar_menu(
            [
              {label: 'Home', path: root_path, controllers: %w[home]},
              {label: 'Developers', path: developers_path, controllers: %w[developers pets]}
            ]
          ) %>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ManyPets</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <div class="wrapper">
      <div class="content">
        <%= render 'layouts/navbar' %>
        <%= render 'layouts/flash' %>
        <main class="main">
          <div class="container">
            <%= yield %>
          </div>
        </main>
        <%= render 'layouts/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/pets/_form.html.erb
<%= render 'layouts/errors', :errors => pet.errors %>
<div class="row">
  <div class="col m12">
    <div class="card-panel white">
      <%= form_for pet, url: url , method: method do |f| %>
        <%= f.label :name %>
        <%= f.text_field :name %>
        <%= f.label :age %>
        <%= f.number_field :age %>

        <div class="vertical-separator"></div>

        <%= f.radio_button(:gender, 'Male', checked: true) %>
        <%= f.label(:gender, 'Male', for: 'pet_gender_male') %>
        <%= f.radio_button(:gender, 'Female') %>
        <%= f.label(:gender, 'Female', for: 'pet_gender_female') %>

        <div class="vertical-separator"></div>

        <%= f.label :category %>
        <%= f.select(:category, Pet.categories.keys) %>

        <div class="vertical-separator"></div>

        <%= f.label :alive %>
        <div class="switch">
          <label>
            No
            <%= f.check_box :alive %>
            <span class="lever"></span>
            Yes
          </label>
        </div>
        <div class="vertical-separator-lg"></div>
        <%= f.submit :class => 'btn btn-primary white-text' %>
        <%= link_to('back', _back_url, :class => 'btn red')%>
      <% end %>
    </div>
  </div>
</div>

app/views/pets/edit.html.erb
<%= render 'pets/form', url: developer_pet_path(developer, pet), method: 'patch' %>

app/views/pets/new.html.erb
<%= render 'pets/form', url: developer_pets_path(developer), method: 'post' %>